services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=vector_db'
      - 'POSTGRES_PASSWORD=Amaan@123'
      - 'POSTGRES_USER=Amaan'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4                                 # official pgAdmin4 :contentReference[oaicite:7]{index=7}
    container_name: pgadmin
    environment:
      - 'PGADMIN_DEFAULT_EMAIL: admin@admin.com'
      # default login email :contentReference[oaicite:8]{index=8}
      - 'PGADMIN_DEFAULT_PASSWORD: admin'
      # default login password :contentReference[oaicite:9]{index=9}
    ports:
      - "8090:80"                                         # access pgAdmin at http://localhost:8080 :contentReference[oaicite:10]{index=10}
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
    pgdata:                                                # named volume for PostgreSQL :contentReference[oaicite:12]{index=12}
    pgadmin_data:
